require("user_plugins.p_emmet").after()
require("user_plugins.c_treesitter").after()
require("user_plugins.p_telescope").after()
require("user_plugins.p_cmp").after()
require("user_plugins.c_lspconfig").after()
require("user_plugins.p_lualine").after()
require("user_plugins.p_nord").after()
